networks:
  ${default.organisation}:
    external: true
services:
  aiostreams:
    environment:
      ADDON_ID: ${service.fqdn}
      DEFAULT_TIMEOUT: 5000
      SECRET_KEY: ${sha256(service.secret_hash)}
    image: ghcr.io/viren070/aiostreams:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
