networks:
  ${default.organisation}:
    external: true
services:
  beets:
    environment:
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: keyfinder-cli
      INSTALL_PIP_PACKAGES:
      TZ: ${server.config.timezone}
    image: linuxserver/beets:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8337}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - /mnt/truenas-nvme/beets:/music
      - /mnt/truenas/music:/downloads
      - data:/config
volumes:
  data:
