networks:
  ${default.organisation}:
    external: true
services:
  beszel:
    environment:
      USER_CREATION: true
    image: henrygd/beszel
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8090}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/beszel_data
volumes:
  data:
