services:
  beszel-agent:
    environment:
      KEY: ${service.secrets.public_key}
    image: henrygd/beszel-agent
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
