networks:
  ${default.organisation}:
    external: true
services:
  calibre-web-automated:
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
      PGID: 568
      PUID: 568
      TZ: ${server.config.timezone}
    image: crocodilestick/calibre-web-automated:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8083}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - /mnt/truenas-nvme/calibre/calibre:/calibre-library
      - /mnt/truenas-nvme/calibre/ingest:/cwa-book-ingest
      - data:/config
volumes:
  data:
