networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
      TZ: ${server.config.timezone}
    image: linuxserver/calibre-web
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8083}}"
    restart: unless-stopped
    volumes:
      - data:/config
      - /Volumes/Media/Books:/books
volumes:
  data:
