networks:
  ${default.organisation}:
    external: true
services:
  service:
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
      TZ: ${server.config.timezone}
    image: crocodilestick/calibre-web-automated
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8083}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - /mnt/truenas/books/calibre:/calibre-library
      - /mnt/truenas/books/unsorted:/cwa-book-ingest
      - data:/config
volumes:
  data:
