networks:
  ${default.organisation}:
    external: true
services:
  changedetection:
    environment:
      BASE_URL: ${service.url}
      PLAYWRIGHT_DRIVER_URL: ws://sockpuppetbrowser:3000
      TZ: ${server.config.timezone}
      USE_X_SETTINGS: 1
    image: dgtlmoon/changedetection.io:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 5000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/datastore
  sockpuppetbrowser:
      cap_add:
        - SYS_ADMIN
      environment:
        MAX_CONCURRENT_CHROME_PROCESSES: 10
        SCREEN_DEPTH: 16
        SCREEN_HEIGHT: 1024
        SCREEN_WIDTH: 1920
      image: dgtlmoon/sockpuppetbrowser:latest
      restart: unless-stopped
volumes:
  data:
