networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    environment:
      COMMAFEED_PASSWORD_RECOVERY_ENABLED: true
      QUARKUS_MAILER_FROM: ${default.email}
      QUARKUS_MAILER_HOST: ${service.mail.host}
      QUARKUS_MAILER_PASSWORD: ${service.mail.password}
      QUARKUS_MAILER_PORT: ${service.mail.port}
      QUARKUS_MAILER_TLS: true
      QUARKUS_MAILER_USERNAME: ${service.mail.username}
    image: athou/commafeed:latest-h2-jvm
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8082}}"
    restart: unless-stopped
    volumes:
      - data:/commafeed/data
volumes:
  data:
