networks:
  ${default.organisation}:
    external: true
services:
  convertx:
    environment:
      ALLOW_UNAUTHENTICATED: true
    image: ghcr.io/c4illin/convertx:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
