networks:
  ${default.organisation}:
    external: true
services:
  cyberchef:
    image: mpepping/cyberchef:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
