networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    image: mpepping/cyberchef
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8000}}"
    restart: unless-stopped
