networks:
  ${default.organisation}:
    external: true
services:
  dailydisplay:
    environment:
      CONFIG: ${service.config}
    image: ghcr.io/maxexcloo/dailydisplay:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 7777}}"
    networks:
      - default
      - ${default.organisation}
    ports:
      - 7777:7777
    restart: unless-stopped
