
services:
  dailydisplay:
    environment:
      CONFIG: '${jsonencode(service.config)}'
    image: ghcr.io/maxexcloo/dailydisplay
    ports:
      - ${service.port}:8000
    restart: unless-stopped
