networks:
  default:
    external: true
    name: ${default.organisation}
services:
%{ for i in range(1, service.config.count + 1) ~}
  service-${i}:
    container_name: ${service.service}-service-${i}
    environment:
      ACCESS_TOKEN: ${service.config.access_token}
      LABELS: ${server.location},${server.name},${service.platform},${service.service}
      REPO_URL: ${service.config.repo_url}
      RUNNER_NAME: ${service.platform}-${server.name}-${i}
    image: myoung34/github-runner
    restart: unless-stopped
    security_opt:
      - label:disable
    volumes:
%{ for path in server.user.sftp_paths ~}
%{ if path != "/" ~}
      - ${path}:${path}
%{ endif ~}
%{ endfor ~}
%{ endfor ~}
