networks:
  ${default.organisation}:
    external: true
services:
  grafana:
    environment:
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: false
      GF_AUTH_GENERIC_OAUTH_AUTH_STYLE: AutoDetect
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${default.oidc_url}/authorize
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: false
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${service.config.oidc_client_id}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${service.config.oidc_client_secret}
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_NAME: email:primary
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: ${default.oidc_title}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid email profile"
      GF_AUTH_GENERIC_OAUTH_SKIP_ORG_ROLE_SYNC: true
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${default.oidc_url}/api/oidc/token
      GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP: true
      GF_SECURITY_ADMIN_EMAIL: ${service.username}
      GF_SECURITY_ADMIN_PASSWORD: ${service.password}
      GF_SECURITY_ADMIN_USER: ${service.username}
      GF_SERVER_ROOT_DOMAIN: ${service.fqdn}
      GF_SERVER_ROOT_URL: ${service.url}
      GF_SMTP_ENABLED: true
      GF_SMTP_FROM_ADDRESS: ${default.email}
      GF_SMTP_FROM_NAME: ${service.title}
      GF_SMTP_HOST: ${service.mail.host}:465
      GF_SMTP_PASSWORD: ${service.mail.password}
      GF_SMTP_USERNAME: ${service.mail.username}
    image: grafana/grafana
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/var/lib/grafana
volumes:
  data:
