networks:
  ${default.organisation}:
    external: true
services:
  service:
    environment:
      GF_SECURITY_ADMIN_EMAIL: ${service.username}
      GF_SECURITY_ADMIN_PASSWORD: ${service.password}
      GF_SECURITY_ADMIN_USER: ${service.username}
      GF_SERVER_ROOT_DOMAIN: ${service.fqdn}
      GF_SERVER_ROOT_URL: ${service.url}
      GF_SMTP_ENABLED: true
      GF_SMTP_FROM_ADDRESS: ${default.email}
      GF_SMTP_FROM_NAME: ${service.title}
      GF_SMTP_HOST: ${service.mail.host}:${service.mail.port}
      GF_SMTP_PASSWORD: ${service.mail.password}
      GF_SMTP_USERNAME: ${service.mail.username}
    image: grafana/grafana
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/var/lib/grafana
volumes:
  data:
