networks:
  ${default.organisation}:
    external: true
services:
  config:
    command: bash -c "${config}"
    image: bash:5
    volumes:
      - config:/app/config
  homepage:
    depends_on:
      config:
        condition: service_completed_successfully
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${service.fqdn}
    image: ghcr.io/gethomepage/homepage:v1
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - config:/app/config
volumes:
  config:
