networks:
  ${default.organisation}:
    external: true
services:
  immich-power-tools:
    environment:
      EXTERNAL_IMMICH_URL: ${service.config.external_immich_url}
      GEMINI_API_KEY: ${service.config.gemini_api_key}
      GOOGLE_MAPS_API_KEY: ${service.config.google_maps_api_key}
      IMMICH_API_KEY: ${service.config.immich_api_key}
      IMMICH_URL: ${service.config.immich_url}
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/varun-raj/immich-power-tools
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
