networks:
  ${default.organisation}:
    external: true
services:
  immich:
    depends_on:
      - postgres
      - redis
    environment:
      DB_DATABASE_NAME: ${service.database.name}
      DB_HOSTNAME: postgres
      DB_PASSWORD: ${service.database.password}
      DB_USERNAME: ${service.database.username}
      REDIS_HOSTNAME: redis
      TZ: ${server.config.timezone}
    image: ghcr.io/imagegenius/immich
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/config
      - photos:/photos
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
volumes:
  data:
  photos:
  postgres:
