networks:
  ${default.organisation}:
    external: true
services:
  it-tools:
    image: corentinth/it-tools:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
