networks:
  ${default.organisation}:
    external: true
services:
  linkwarden:
    depends_on:
      - meilisearch
      - postgres
    environment:
      AUTHELIA_CLIENT_ID: ${service.config.oidc_client_id}
      AUTHELIA_CLIENT_SECRET: ${service.config.oidc_client_secret}
      AUTHELIA_WELLKNOWN_URL: ${default.oidc_url}/.well-known/openid-configuration
      DATABASE_URL: postgres://${service.database.username}:${service.database.password}@postgres/${service.database.name}
      EMAIL_FROM: ${default.email}
      EMAIL_SERVER: smtp://${service.mail.username}:${service.mail.password}@${service.mail.host}:${service.mail.port}
      NEXTAUTH_SECRET: ${server.secret_hash}
      NEXTAUTH_URL: ${service.url}/api/v1/auth
      NEXT_PUBLIC_AUTHELIA_ENABLED: true
      NEXT_PUBLIC_EMAIL_PROVIDER: true
      TZ: ${server.config.timezone}
    image: ghcr.io/linkwarden/linkwarden
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/data/data
  meilisearch:
    image: getmeili/meilisearch:v1
    restart: unless-stopped
    volumes:
      - meilisearch:/meili_data
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  data:
  meilisearch:
  postgres:
