networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    environment:
      BASE_URL: ${service.url}
      OPENAI_API_KEY: ${service.config.openai_api_key}
      SMTP_FROM_EMAIL: ${default.email}
      SMTP_FROM_NAME: ${service.title}
      SMTP_HOST: ${service.mail.host}
      SMTP_PASSWORD: ${service.mail.password}
      SMTP_PORT: ${service.mail.port}
      SMTP_USER: ${service.mail.username}
      TZ: ${server.config.timezone}
    image: ghcr.io/mealie-recipes/mealie
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 9000}}"
    restart: unless-stopped
    volumes:
      - data:/app/data
volumes:
  data:
