networks:
  ${default.organisation}:
    external: true
services:
  mealie:
    environment:
      BASE_URL: ${service.url}
      OIDC_AUTH_ENABLED: true
      OIDC_CLIENT_ID: ${service.config.oidc_client_id}
      OIDC_CLIENT_SECRET: ${service.config.oidc_client_secret}
      OIDC_CONFIGURATION_URL: ${default.oidc_url}/.well-known/openid-configuration
      OIDC_PROVIDER_NAME: ${default.oidc_title}
      OPENAI_API_KEY: ${service.config.openai_api_key}
      OPENAI_BASE_URL: ${service.config.openai_base_url}
      OPENAI_MODEL: ${service.config.openai_model}
      SMTP_FROM_EMAIL: ${default.email}
      SMTP_FROM_NAME: ${service.title}
      SMTP_HOST: ${service.mail.host}
      SMTP_PASSWORD: ${service.mail.password}
      SMTP_PORT: ${service.mail.port}
      SMTP_USER: ${service.mail.username}
      TZ: ${server.config.timezone}
    image: ghcr.io/mealie-recipes/mealie:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 9000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/app/data
volumes:
  data:
