networks:
  ${default.organisation}:
    external: true
services:
  miniflux:
    depends_on:
      - postgres
    environment:
      ADMIN_PASSWORD: ${service.password}
      ADMIN_USERNAME: ${service.username}
      BASE_URL: ${service.url}
      CREATE_ADMIN: 1
      DATABASE_URL: postgres://${service.database.username}:${service.database.password}@postgres/${service.database.name}?sslmode=disable
      RUN_MIGRATIONS: 1
    image: miniflux/miniflux
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
