networks:
  ${default.organisation}:
    external: true
services:
  service:
    image: germannewsmaker/myspeed
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 5216}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/myspeed/data
volumes:
  data:
