networks:
  ${default.organisation}:
    external: true
services:
  n8n:
    depends_on:
      - postgres
    environment:
      DB_POSTGRESDB_DATABASE: ${service.database.name}
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PASSWORD: ${service.database.password}
      DB_POSTGRESDB_USER: ${service.database.username}
      DB_TYPE: postgresdb
      GENERIC_TIMEZONE: ${server.config.timezone}
      N8N_HOST: ${service.fqdn}
      N8N_PROTOCOL: https
      WEBHOOK_URL: ${service.url}
    image: n8nio/n8n:stable
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 5678}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/home/node/.n8n
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  data:
  postgres:
