networks:
  default:
    external: true
    name: ${default.organisation}
services:
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  service:
    depends_on:
      - postgres
    environment:
      NC_DB: pg://${service.portainer_name}-postgres-1:5432?d=${service.database.name}&p=${service.database.password}&u=${service.database.username}
    image: nocodb/nocodb
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/usr/app/data
volumes:
  data:
  postgres:
