networks:
  ${default.organisation}:
    external: true
services:
  nocodb:
    depends_on:
      - postgres
    environment:
      NC_DB: pg://postgres:5432?d=${service.database.name}&p=${service.database.password}&u=${service.database.username}
    image: nocodb/nocodb:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/usr/app/data
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  data:
  postgres:
