networks:
  ${default.organisation}:
    external: true
services:
%{ if contains(server.flags, "cloudflare_proxy") == false ~}
  external:
    image: openspeedtest/latest:latest
    labels:
      caddy: ${service.service}.${server.fqdn_external}
      caddy.import: external
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
%{ endif ~}
  internal:
    image: openspeedtest/latest:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
