networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    environment:
      ENV: dev
    image: ghcr.io/open-webui/open-webui
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
volumes:
  data:
