networks:
  ${default.organisation}:
    external: true
services:
  service:
    image: ghcr.io/open-webui/open-webui
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
volumes:
  data:
