networks:
  ${default.organisation}:
    external: true
services:
  paperless-ai:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: clusterzx/paperless-ai:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/app/data
volumes:
  data:
