networks:
  ${default.organisation}:
    external: true
services:
  gotenberg:
    command:
      - "gotenberg"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--chromium-disable-javascript=true"
    image: gotenberg/gotenberg:8
    restart: unless-stopped
  paperless-ngx:
    depends_on:
      - gotenberg
      - postgres
      - redis
      - tika
    environment:
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: ${service.database.name}
      PAPERLESS_DBPASS: ${service.database.password}
      PAPERLESS_DBUSER: ${service.database.username}
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_SECRET_KEY: ${service.secret_hash}
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"${default.oidc_id}","name":"${default.oidc_name}","client_id":"${service.config.oidc_client_id}","secret":"${service.config.oidc_client_secret}","settings":{"server_url":"${default.oidc_issuer}"}}]}}' 
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIME_ZONE: ${server.config.timezone}
      PAPERLESS_URL: ${service.url}
    image: ghcr.io/paperless-ngx/paperless-ngx
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8000}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - /mnt/truenas-nvme/paperless/consume:/usr/src/paperless/consume
      - /mnt/truenas-nvme/paperless/data:/usr/src/paperless/data
      - /mnt/truenas-nvme/paperless/export:/usr/src/paperless/export
      - /mnt/truenas-nvme/paperless/media:/usr/src/paperless/media
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data
  tika:
    image: apache/tika
    restart: unless-stopped
volumes:
  postgres:
  redis:
