networks:
  ${default.organisation}:
    external: true
services:
  planka:
    depends_on:
      - postgres
    environment:
      BASE_URL: ${service.url}
      DATABASE_URL: postgresql://${service.database.username}:${service.database.password}@postgres/${service.database.name}
      OIDC_CLIENT_ID: ${service.config.oidc_client_id}
      OIDC_CLIENT_SECRET: ${service.config.oidc_client_secret}
      OIDC_ISSUER: ${default.oidc_url}
      SECRET_KEY: ${service.secret_hash}
      SMTP_FROM: ${default.email}
      SMTP_HOST: ${service.mail.host}
      SMTP_PASSWORD: ${service.mail.password}
      SMTP_PORT: ${service.mail.port}
      SMTP_SECURE: true
      SMTP_USER: ${service.mail.username}
    image: ghcr.io/plankanban/planka
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 1337}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - attachments:/app/private/attachments
      - project-background-images:/app/public/project-background-images
      - user-avatars:/app/public/user-avatars
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  attachments:
  postgres:
  project-background-images:
  user-avatars:
