networks:
  ${default.organisation}:
    external: true
services:
  pocket-id:
    environment:
      APP_NAME: ${service.name}
      EMAIL_ONE_TIME_ACCESS_ENABLED: true
      EMAILS_VERIFIED: true
      MAXMIND_LICENSE_KEY: ${service.config.maxmind_license_key}
      PUBLIC_APP_URL: ${service.url}
      PUBLIC_UI_CONFIG_DISABLED: true
      SESSION_DURATION: 1440
      SMTP_FROM: ${default.email}
      SMTP_HOST: ${service.mail.host}
      SMTP_PASSWORD: ${service.mail.password}
      SMTP_PORT: ${service.mail.port}
      SMTP_TLS: tls
      SMTP_USER: ${service.mail.username}
      TRUST_PROXY: true
    image: ghcr.io/pocket-id/pocket-id
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
volumes:
  data:
