networks:
  ${default.organisation}:
    external: true
services:
  config:
    command: bash -c "${config}"
    image: bash
    volumes:
      - config:/config
  service:
    command:
      - --config.file=/config/config.yaml
      - --storage.tsdb.retention.time=744h
      - --web.enable-lifecycle
    depends_on:
      config:
        condition: service_completed_successfully
    image: prom/prometheus
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 9090}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - config:/config
      - data:/prometheus
volumes:
  config:
  data:
