networks:
  ${default.organisation}:
    external: true
services:
%{ if can(service.config.ctrld_resolver) ~}
  ctrld:
    command: --cd=${service.config.ctrld_resolver}
    dns: 127.0.0.1
    image: controldns/ctrld:latest
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
%{ endif ~}
  redlib:
    environment:
      REDLIB_DEFAULT_REMOVE_DEFAULT_FEEDS: on
      REDLIB_DEFAULT_SHOW_NSFW: ${service.config.show_nsfw}
      REDLIB_DEFAULT_SUBSCRIPTIONS: ${join("+", service.config.subscriptions)}
      REDLIB_DEFAULT_USE_HLS: on
      REDLIB_FULL_URL: ${service.url}
      REDLIB_ROBOTS_DISABLE_INDEXING: on
    image: quay.io/redlib/redlib:latest
%{ if can(service.config.ctrld_resolver) ~}
    network_mode: service:ctrld
%{ else ~}
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
%{ endif ~}
    restart: unless-stopped
