networks:
  default:
    external: true
    name: ${default.organisation}
services:
  network:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      SERVER_CITIES: ${service.secrets.server_cities}
      VPN_SERVICE_PROVIDER: ${service.secrets.vpn_service_provider}
      VPN_TYPE: ${service.secrets.vpn_type}
      WIREGUARD_ADDRESSES: ${service.secrets.wireguard_addresses}
      WIREGUARD_PRESHARED_KEY: ${service.secrets.wireguard_preshared_key}
      WIREGUARD_PRIVATE_KEY: ${service.secrets.wireguard_private_key}
    image: qmcgaw/gluetun
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro
  service:
    environment:
      REDLIB_DEFAULT_SUBSCRIPTIONS: 3dprinting+apple+askanaustralian+ausfinance+aussiefrugal+australia+catastrophicfailure+datahoarder+emulation+emulationonandroid+flashlight+flipperzero+games+guysbeingdudes+handhelds+hardware+homeassistant+homelab+homenetworking+internetisbeautiful+korea+linux+living_in_korea+minilab+minimalism+minipcs+movies+odinhandheld+outoftheloop+youtubehaiku+retroarch+retroid+roms+sbcgaming+selfhosted+sideloaded+space+steamdeck+sydney+sysadmin+television+thatlookedexpensive+trance+travel+trimui
      REDLIB_ROBOTS_DISABLE_INDEXING: on
    image: quay.io/redlib/redlib
    network_mode: service:network
    restart: unless-stopped
