networks:
  default:
    external: true
    name: ${default.organisation}
services:
  network:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      SERVER_CITIES: ${service.config.gluetun_server_cities}
      VPN_SERVICE_PROVIDER: ${service.config.gluetun_vpn_service_provider}
      VPN_TYPE: ${service.config.gluetun_vpn_type}
      WIREGUARD_ADDRESSES: ${service.config.gluetun_wireguard_addresses}
      WIREGUARD_PRESHARED_KEY: ${service.config.gluetun_wireguard_preshared_key}
      WIREGUARD_PRIVATE_KEY: ${service.config.gluetun_wireguard_private_key}
    image: qmcgaw/gluetun
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro
  service:
    environment:
      REDLIB_DEFAULT_SHOW_NSFW: ${service.config.redlib_show_nsfw}
      REDLIB_DEFAULT_SUBSCRIPTIONS: ${join("+", service.config.redlib_subscriptions)}
      REDLIB_DEFAULT_USE_HLS: on
      REDLIB_ENABLE_RSS: on
      REDLIB_FULL_URL: ${service.url}
      REDLIB_ROBOTS_DISABLE_INDEXING: on
    image: quay.io/redlib/redlib
    network_mode: service:network
    restart: unless-stopped
