networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    image: diygod/rsshub:chromium-bundled
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 1200}}"
    restart: unless-stopped
