networks:
  ${default.organisation}:
    external: true
services:
  service:
    image: diygod/rsshub:chromium-bundled
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 1200}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
