networks:
  default:
    external: true
    name: ${default.organisation}
services:
  service:
    environment:
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
      LANGS: en_GB
    image: stirlingtools/stirling-pdf
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - customfiles:/customFiles
      - data:/configs
      - tessdata:/usr/share/tessdata
volumes:
  customfiles:
  data:
  tessdata:
