networks:
  ${default.organisation}:
    external: true
services:
  stirling-pdf:
    environment:
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true
      LANGS: en_GB
    image: stirlingtools/stirling-pdf
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - customfiles:/customFiles
      - data:/configs
      - tessdata:/usr/share/tessdata
volumes:
  customfiles:
  data:
  tessdata:
