networks:
  ${default.organisation}:
    external: true
services:
  service:
    image: syncthing/syncthing
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8384}}"
    networks:
      - default
      - ${default.organisation}
    ports:
      - 22000:22000
      - 22000:22000/udp
    restart: unless-stopped
    volumes:
      - data:/var/syncthing
      - /home/max.schaefer:/sync
volumes:
  data:
