networks:
  ${default.organisation}:
    external: true
services:
  watchtower:
    environment:
      TZ: ${server.config.timezone}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATION_URL: smtp://${service.mail.username}:${service.mail.password}@${service.mail.host}:${service.mail.port}/?from=${default.email}&to=${default.email}
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${service.server}
      WATCHTOWER_REMOVE_VOLUMES: true
      WATCHTOWER_SCHEDULE: "@weekly"
    image: containrrr/watchtower
    labels:
      caddy: ${service.fqdn}
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
