networks:
  ${default.organisation}:
    external: true
services:
  mariadb:
    environment:
      MARIADB_DATABASE: ${service.database.name}
      MARIADB_PASSWORD: ${service.database.password}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${service.database.username}
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${service.database.name}
      WORDPRESS_DB_PASSWORD: ${service.database.password}
      WORDPRESS_DB_USER: ${service.database.username}
    image: wordpress:6
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - data:/var/www/html
volumes:
  data:
  mariadb:
