networks:
  ${default.organisation}:
    external: true
services:
  config:
    command: bash -c "${config}"
    image: bash
    volumes:
      - config:/app/config
  error-pages:
    environment:
      TEMPLATE_NAME: lost-in-space
    image: ghcr.io/tarampampam/error-pages
    labels:
      caddy: ${service.dns_zone} ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.0_reverse_proxy: "/.well-known/webfinger finger"
      caddy.1_reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
  finger:
    environment:
      WF_FINGER_FILE: /config/finger.json
      WF_PORT: 80
    image: git.maronato.dev/maronato/finger
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - config:/config
volumes:
  config:
