networks:
  ${default.organisation}:
    external: true
services:
  config:
    command: bash -c "${config}"
    image: bash:5
    volumes:
      - config:/config
  error-pages:
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.redir: /.well-known/webfinger* https://${service.dns_zone}{uri} permanent
      caddy.reverse_proxy: "{{upstreams 8080}}"
    environment:
      TEMPLATE_NAME: lost-in-space
    image: ghcr.io/tarampampam/error-pages:latest
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
  finger:
    depends_on:
      config:
        condition: service_completed_successfully
    environment:
      WF_FINGER_FILE: /config/finger.json
    image: ghcr.io/artemstepanov/go-finger:main
    labels:
      caddy: ${service.dns_zone}
      caddy.@match.not: path /.well-known/webfinger*
      caddy.import: ${service.zone}
      caddy.redir: "@match https://${service.fqdn}{uri} permanent"
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - default
      - ${default.organisation}
    restart: unless-stopped
    volumes:
      - config:/config
volumes:
  config:
