networks:
  default:
    external: true
    name: caddy
services:
  external:
    image: traefik/whoami
    labels:
      caddy: whoami.${SERVER_FQDN_EXTERNAL}
      caddy.reverse_proxy: "{{upstreams 80}}"
    restart: unless-stopped
  internal:
    image: traefik/whoami
    labels:
      caddy: whoami.${SERVER_FQDN_INTERNAL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls.dns: cloudflare ${SERVER_CLOUDFLARE_API_TOKEN}
      caddy.tls.resolvers: 1.1.1.1
    restart: unless-stopped
