networks:
  default:
    external: true
    name: docker
services:
  caddy:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/maxexcloo/caddy
    labels:
      caddy.email: EMAIL
      caddy.tls.dns_challenge_override_domain: excloo.duckdns.org 
      caddy.tls.dns: duckdns TOKEN
      caddy.tls.resolvers: 1.1.1.1
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
volumes:
  caddy_data:
