networks:
  default:
    external: true
    name: caddy
services:
  daily:
    environment:
      AWS_ACCESS_KEY_ID: ${SERVER_B2_BUCKET_APPLICATION_KEY_ID}
      AWS_ENDPOINT: ${SERVER_B2_BUCKET_ENDPOINT}
      AWS_S3_BUCKET_NAME: ${SERVER_B2_BUCKET_BUCKET_NAME}
      AWS_SECRET_ACCESS_KEY: ${SERVER_B2_BUCKET_APPLICATION_KEY}
      BACKUP_COMPRESSION: zst
      BACKUP_CRON_EXPRESSION: "@daily"
      BACKUP_EXCLUDE_REGEXP: '[a-f0-9]{64}\/|backingFsBlockDev$|immich_.*\/|metadata\.db$'
      BACKUP_FILENAME: daily-backup-%Y-%m-%dT%H-%M-%S.tar.zst
      BACKUP_PRUNING_PREFIX: daily-backup-
      BACKUP_RETENTION_DAYS: 7
      GPG_PASSPHRASE: ${SECRET_GPG_PASSPHRASE}
      NOTIFICATION_URLS: smtp://resend:${SERVER_RESEND_API_KEY}@smtp.resend.com:465/?fromAddress=${DEFAULT_EMAIL}&toAddresses=${DEFAULT_EMAIL}
    image: offen/docker-volume-backup
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/docker/volume:/backup:ro
  weekly:
    environment:
      AWS_ACCESS_KEY_ID: ${SERVER_B2_BUCKET_APPLICATION_KEY_ID}
      AWS_ENDPOINT: ${SERVER_B2_BUCKET_ENDPOINT}
      AWS_S3_BUCKET_NAME: ${SERVER_B2_BUCKET_BUCKET_NAME}
      AWS_SECRET_ACCESS_KEY: ${SERVER_B2_BUCKET_APPLICATION_KEY}
      BACKUP_COMPRESSION: zst
      BACKUP_CRON_EXPRESSION: "@weekly"
      BACKUP_EXCLUDE_REGEXP: '[a-f0-9]{64}\/|backingFsBlockDev$|immich_.*\/|metadata\.db$'
      BACKUP_FILENAME: weekly-backup-%Y-%m-%dT%H-%M-%S.tar.zst
      BACKUP_PRUNING_PREFIX: weekly-backup-
      BACKUP_RETENTION_DAYS: 31
      GPG_PASSPHRASE: ${SECRET_GPG_PASSPHRASE}
      NOTIFICATION_URLS: smtp://resend:${SERVER_RESEND_API_KEY}@smtp.resend.com:465/?fromAddress=${DEFAULT_EMAIL}&toAddresses=${DEFAULT_EMAIL}
    image: offen/docker-volume-backup
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/lib/docker/volume:/backup:ro
