  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Routers"
    name: "au"
    url: "icmp://au"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers"
    name: "au-mini"
    url: "icmp://au-mini"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "VMs"
    name: "au-oracle"
    url: "icmp://au-oracle"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers"
    name: "au-pi"
    url: "icmp://au-pi"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Routers"
    name: "kr"
    url: "icmp://kr"
