networks:
  default:
    external: true
    name: caddy
services:
  redlib:
    environment:
      LIBREDDIT_DEFAULT_HIDE_AWARDS: on
      LIBREDDIT_DEFAULT_SUBSCRIPTIONS: apple+askanaustralian+ausfinance+aussiecasual+australia+catastrophicfailure+datahoarder+emulation+emulationonandroid+flipperzero+internetisbeautiful+korea+linux+living_in_korea+miyoomini+movies+odinhandheld+outoftheloop+piracy+retroid+roms+sbcgaming+selfhosted+sideloaded+steamdeck+sydney+television+trance
      LIBREDDIT_DEFAULT_USE_HLS: on
      LIBREDDIT_ROBOTS_DISABLE_INDEXING: on
    image: quay.io/redlib/redlib
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
