- Cloud:
  - Excloo GitHub Readme Stats:
    - href: https://github-readme-stats.excloo.com/
      icon: github-light
  - Excloo Uptime:
    - href: https://uptime.excloo.com/
      icon: gatus
- Kimbap TrueNAS (KR):
  - File Browser:
    - href: https://kimbap.kr.excloo.org:30051/
      icon: filebrowser
  - Speedtest:
    - href: https://speedtest.kimbap.kr.excloo.org/
      icon: openspeedtest
  - Syncthing:
    - href: http://kimbap.kr.excloo.org:20910/
      icon: syncthing
  - TrueNAS:
    - href: https://kimbap.kr.excloo.org:8443/
      icon: truenas
- Mini (AU):
  - Excloo Books:
    - href: https://books.excloo.org/
      icon: calibre
  - Excloo Chat:
    - href: https://chat.excloo.org/
      icon: open-webui-light
  - Excloo Home:
    - href: https://home.excloo.org/
      icon: homepage
  - Excloo Photos:
    - href: https://photos.excloo.org/
      icon: immich
  - Portainer:
    - href: https://portainer.excloo.org/
      icon: portainer
  - Speedtest:
    - href: https://speedtest.mini.au.excloo.org/
      icon: openspeedtest
  - Syncthing:
    - href: http://mini.au.excloo.org:8384/
      icon: syncthing
- Oracle (AU):
  - Excloo N8N:
    - href: https://n8n.excloo.com/
      icon: n8n
  - Excloo NocoDB:
    - href: https://nocodb.excloo.org/
      icon: nocodb
  - Excloo RSSHub:
    - href: https://rsshub.excloo.org/
      icon: rsshub
  - Excloo Reader:
    - href: https://reader.excloo.com/
      icon: commafeed
  - Excloo Reddit:
    - href: https://reddit.excloo.com/
      icon: libreddit
  - Excloo Tools:
    - href: https://tools.excloo.com/
      icon: cyberchef
  - Speedtest (External):
    - href: https://speedtest.oracle.au.excloo.net/
      icon: openspeedtest
  - Speedtest (Internal):
    - href: https://speedtest.oracle.au.excloo.org/
      icon: openspeedtest
- Pie (AU):
  - Proxmox:
    - href: https://pie.au.excloo.org:8006/
      icon: proxmox
- Pie HAOS (AU):
  - Home Assistant:
    - href: https://haos.pie.au.excloo.org/
      icon: home-assistant
- Pie TrueNAS (AU):
  - CubeBackup:
    - href: https://cubebackup.excloo.org/
      icon: google
  - File Browser:
    - href: https://truenas.pie.au.excloo.org:30051/
      icon: filebrowser
  - Speedtest:
    - href: https://speedtest.truenas.pie.au.excloo.org/
      icon: openspeedtest
  - Syncthing:
    - href: http://truenas.pie.au.excloo.org:20910/
      icon: syncthing
  - TrueNAS:
    - href: https://truenas.pie.au.excloo.org:8443/
      icon: truenas
