- glances:
    label: Mini (AU)
    uptime: true
    url: https://glances.mini.au.excloo.org
    version: 4
- glances:
    label: Oracle (AU)
    uptime: true
    url: https://glances.oracle.au.excloo.org
    version: 4
- glances:
    label: Pie TrueNAS (AU)
    uptime: true
    url: https://glances.truenas.pie.au.excloo.org
    version: 4
- glances:
    label: Kimbap TrueNAS (KR)
    uptime: true
    url: https://glances.kimbap.kr.excloo.org
    version: 4
