- au-mini:
  - SpeedTest (External):
    - href: https://speedtest.mini.excloo.net
  - SpeedTest (Internal):
    - href: https://speedtest.mini.excloo.org
  - Excloo Books:
    - href: https://books.excloo.com/
  - Excloo Chat:
    - href: https://chat.excloo.com/
  - Excloo Photos:
    - href: https://photos.excloo.com/
  - Home:
    - href: https://home.excloo.org/
  - Portainer:
    - href: https://portainer.excloo.org/
- au-oracle:
  - SpeedTest (External):
    - href: https://speedtest.oracle.excloo.net
  - SpeedTest (Internal):
    - href: https://speedtest.oracle.excloo.org
  - Excloo N8N:
    - href: https://n8n.excloo.com/
  - Excloo NocoDB:
    - href: https://nocodb.excloo.com/
  - Excloo Reader:
    - href: https://reader.excloo.com/
  - Excloo Reddit:
    - href: https://reddit.excloo.com/
  - Excloo RSSHub:
    - href: https://rsshub.excloo.com/
  - Excloo Tools:
    - href: https://tools.excloo.com/
  - Syncthing (Oracle):
    - href: https://syncthing.oracle.excloo.org/
- Fly:
  - Excloo Uptime:
    - href: https://uptime.excloo.com/
- Native:
  - Syncthing (Mini):
    - href: http://mini.excloo.org:8384/
- TrueNAS:
  - CubeBackup:
    - href: http://gen8.excloo.org:15000/
  - Filebrowser (Gen8):
    - href: https://gen8.excloo.org:30044/
  - Filebrowser (Kimbap):
    - href: https://kimbap.excloo.org:30051/
  - Syncthing (Gen8):
    - href: http://gen8.excloo.org:20910/
  - Syncthing (Kimbap):
    - href: http://kimbap.excloo.org:20910/
- Vercel:
  - Excloo GitHub Readme Stats:
    - href: https://github-readme-stats.excloo.com/
