- Mini (AU):
  - OpenSpeedTest (External):
    - href: https://speedtest.mini.au.excloo.net
      icon: openspeedtest
  - OpenSpeedTest (Internal):
    - href: https://speedtest.mini.au.excloo.org
      icon: openspeedtest
  - Excloo Books:
    - href: https://books.excloo.com/
      icon: calibre
  - Excloo Chat:
    - href: https://chat.excloo.com/
      icon: open-webui-light
  - Excloo Photos:
    - href: https://photos.excloo.com/
      icon: immich
  - Home:
    - href: https://home.excloo.org/
      icon: homepage
  - Portainer:
    - href: https://portainer.excloo.org/
      icon: portainer
  - Syncthing:
    - href: http://mini.au.excloo.org:8384/
      icon: syncthing
- Oracle (AU):
  - OpenSpeedTest (External):
    - href: https://speedtest.oracle.au.excloo.net
      icon: openspeedtest
  - OpenSpeedTest (Internal):
    - href: https://speedtest.oracle.au.excloo.org
      icon: openspeedtest
  - Excloo N8N:
    - href: https://n8n.excloo.com/
      icon: n8n
  - Excloo NocoDB:
    - href: https://nocodb.excloo.com/
      icon: nocodb
  - Excloo Reader:
    - href: https://reader.excloo.com/
      icon: commafeed
  - Excloo Reddit:
    - href: https://reddit.excloo.com/
      icon: libreddit
  - Excloo RSSHub:
    - href: https://rsshub.excloo.com/
      icon: rsshub
  - Excloo Tools:
    - href: https://tools.excloo.com/
      icon: cyberchef
  - Syncthing:
    - href: https://syncthing.oracle.excloo.org/
      icon: syncthing
- Pie (AU):
- Pie TrueNAS (AU):
  - CubeBackup:
    - href: http://truenas.pie.au.excloo.org:8888/
      icon: google
  - Homebridge:
    - href: http://truenas.pie.au.excloo.org:8581/
      icon: homebridge
  - File Browser:
    - href: https://truenas.pie.au.excloo.org:30051/
      icon: filebrowser
  - Syncthing:
    - href: http://truenas.pie.au.excloo.org:20910/
      icon: syncthing
- Kimbap (KR):
  - File Browser:
    - href: https://kimbap.kr.excloo.org:30051/
      icon: filebrowser
  - Syncthing:
    - href: http://kimbap.kr.excloo.org:20910/
      icon: syncthing
- Cloud:
  - Excloo Uptime:
    - href: https://uptime.excloo.com/
      icon: gatus
  - Excloo GitHub Readme Stats:
    - href: https://github-readme-stats.excloo.com/
      icon: github-light
