- au-mini:
  - OpenSpeedTest (External):
    - href: https://speedtest.mini.excloo.net
      icon: openspeedtest
  - OpenSpeedTest (Internal):
    - href: https://speedtest.mini.excloo.org
      icon: openspeedtest
  - Excloo Books:
    - href: https://books.excloo.com/
      icon: calibre-web
  - Excloo Chat:
    - href: https://chat.excloo.com/
      icon: open-webui
  - Excloo Photos:
    - href: https://photos.excloo.com/
      icon: immich
  - Home:
    - href: https://home.excloo.org/
      icon: homepage
  - Portainer:
    - href: https://portainer.excloo.org/
      icon: portainer
  - Syncthing (Mini):
    - href: http://mini.excloo.org:8384/
      icon: syncthing
- au-oracle:
  - OpenSpeedTest (External):
    - href: https://speedtest.oracle.excloo.net
      icon: openspeedtest
  - OpenSpeedTest (Internal):
    - href: https://speedtest.oracle.excloo.org
      icon: openspeedtest
  - Excloo N8N:
    - href: https://n8n.excloo.com/
      icon: n8n
  - Excloo NocoDB:
    - href: https://nocodb.excloo.com/
      icon: nocodb
  - Excloo Reader:
    - href: https://reader.excloo.com/
      icon: commafeed
  - Excloo Reddit:
    - href: https://reddit.excloo.com/
      icon: libreddit
  - Excloo RSSHub:
    - href: https://rsshub.excloo.com/
      icon: rsshub
  - Excloo Tools:
    - href: https://tools.excloo.com/
      icon: cyberchef
  - Syncthing (Oracle):
    - href: https://syncthing.oracle.excloo.org/
      icon: syncthing
  - Filebrowser (Kimbap):
    - href: https://kimbap.excloo.org:30051/
      icon: file-browser
  - Syncthing (Kimbap):
    - href: http://kimbap.excloo.org:20910/
      icon: syncthing
- Cloud:
  - Excloo Uptime:
    - href: https://uptime.excloo.com/
      icon: gatus
  - Excloo GitHub Readme Stats:
    - href: https://github-readme-stats.excloo.com/
      icon: github
