- glances:
    cputemp: true
    label: au-mini
    uptime: true
    url: https://glances.mini.excloo.org
    version: 4
- glances:
    cputemp: true
    label: au-oracle
    uptime: true
    url: https://glances.oracle.excloo.org
    version: 4
