- glances:
    label: Mini (AU)
    uptime: true
    url: http://mini.au.excloo.org:61208
    version: 4
- glances:
    label: Oracle (AU)
    uptime: true
    url: http://oracle.au.excloo.org:61208
    version: 4
- glances:
    label: Pie TrueNAS (AU)
    uptime: true
    url: http://truenas.pie.au.excloo.org:61208
    version: 4
- glances:
    label: Kimbap (KR)
    uptime: true
    url: http://kimbap.kr.excloo.org:61208
    version: 4
