env_file:
  - path: ~/.env/_server.env
networks:
  default:
    external: true
    name: docker
services:
  service:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/maxexcloo/caddy
    labels:
      caddy.email: ${SERVER_EMAIL}
      caddy.tls.dns_challenge_override_domain: ${SERVER_DUCKDNS_DOMAIN}
      caddy.tls.dns: duckdns ${SERVER_DUCKDNS_TOKEN}
      caddy.tls.resolvers: 1.1.1.1
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
volumes:
  data:
