networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      DOCKER_MODS: linuxserver/mods:universal-calibre
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
      TZ: ${SERVER_TIMEZONE}
    image: linuxserver/calibre-web
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.import: ${SERVICE_ZONE}
      caddy.reverse_proxy: "{{upstreams 8083}}"
    restart: unless-stopped
    volumes:
      - data:/config
      - /Volumes/Media/Books:/books
volumes:
  data:
