networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      CF_APP_PUBLICURL: ${SERVICE_URL}
    image: athou/commafeed:latest-h2-jvm
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8082}}"
    restart: unless-stopped
    volumes:
      - data:/commafeed/data
volumes:
  data:
