networks:
  default:
    external: true
    name: docker
services:
  service:
    image: ghcr.io/gchq/cyberchef
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    platform: linux/amd64
    restart: unless-stopped
