networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      GLANCES_OPT: -w
    hostname: ${SERVER_HOST}
    image: nicolargo/glances
    labels:
      caddy: glances.${SERVER_FQDN_INTERNAL}
      caddy.import: ${SERVICE_ZONE}
      caddy.reverse_proxy: "{{upstreams 61208}}"
    pid: host
    ports:
      - 61208:61208
    restart: unless-stopped
    volumes:
      - /etc/os-release:/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock
