networks:
  default:
    external: true
    name: docker
services:
  config:
    command: bash -c "for FILE in $$(env | grep '^SERVICE_CONFIG_.*_PATH=' | cut -d = -f 1); do mkdir -p /data/$$(dirname $${!FILE}); CONTENT_VAR="$${FILE%_PATH}_CONTENT"; echo \"$${!CONTENT_VAR}\" | base64 -d | gunzip > $${!FILE}; done"
    env_file: ../stack.env
    image: bash
    volumes:
      - data:/etc/glances
  service:
    environment:
      GLANCES_OPT: -w
    hostname: ${SERVER_HOST}
    image: nicolargo/glances
    labels:
      caddy: glances.${SERVER_FQDN_INTERNAL}
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 61208}}"
    pid: host
    ports:
      - 61208:61208
    restart: unless-stopped
    volumes:
      - data:/etc/glances
      - /etc/os-release:/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  data:
