networks:
  default:
    external: true
    name: docker
services:
  config:
    command: sh -c 'for FILE in $$(env | grep "^SERVICE_CONFIG_.*_PATH=" | cut -d = -f 1); do eval "v=\$$$$FILE;c=\$${FILE%_PATH}_CONTENT"; mkdir -p /data/$${v%/*}; eval "echo \$$c" | base64 -d | gunzip > /data/$$v; done'
    env_file: ../stack.env
    image: alpine
    volumes:
      - data:/app/config
  service:
    depends_on:
      config:
        condition: service_completed_successfully
    image: ghcr.io/gethomepage/homepage
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.import: ${SERVICE_ZONE}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
    volumes:
      - data:/app/config
volumes:
  data:
