networks:
  default:
    external: true
    name: docker
services:
  config:
    command: bash -c "${config}"
    image: bash
    volumes:
      - config:/app/config
  service:
    depends_on:
      config:
        condition: service_completed_successfully
    image: ghcr.io/gethomepage/homepage
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
    volumes:
      - config:/app/config
volumes:
  config:
