networks:
  default:
    external: true
    name: docker
services:
  config:
    command: sh -c "for FILE in $$(env | grep '^SERVICE_CONFIG_.*_PATH=' | cut -d = -f 1); do mkdir -p /data/$${!FILE%/*}; echo \"$${!FILE%_PATH}_CONTENT\" | base64 -d | gunzip > /data/$${!FILE}; done"
    environment:
      - SERVICE_CONFIG_1_CONTENT
      - SERVICE_CONFIG_1_PATH
      - SERVICE_CONFIG_2_CONTENT
      - SERVICE_CONFIG_2_PATH
      - SERVICE_CONFIG_3_CONTENT
      - SERVICE_CONFIG_3_PATH
      - SERVICE_CONFIG_4_CONTENT
      - SERVICE_CONFIG_4_PATH
      - SERVICE_CONFIG_5_CONTENT
      - SERVICE_CONFIG_5_PATH
    image: alpine
    volumes:
      - data:/app/config
  service:
    depends_on:
      config:
        condition: service_completed_successfully
    image: ghcr.io/gethomepage/homepage
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.import: ${SERVICE_ZONE}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
    volumes:
      - data:/app/config
volumes:
  data:
