env_file:
  - path: ~/.env/_server.env
    required: false
  - path: ~/.env/isponsorblocktv.env
    required: false
services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv
    network_mode: host
    restart: unless-stopped
    volumes:
      - data:/app/data
volumes:
  data:
