networks:
  default:
    external: true
    name: docker
services:
  postgres:
    environment:
      POSTGRES_DB: ${service.database.name}
      POSTGRES_PASSWORD: ${service.database.password}
      POSTGRES_USER: ${service.database.username}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  service:
    depends_on:
      - postgres
    environment:
      DB_POSTGRESDB_DATABASE: ${service.database.name}
      DB_POSTGRESDB_HOST: ${service.service}-postgres-1
      DB_POSTGRESDB_PASSWORD: ${service.database.password}
      DB_POSTGRESDB_USER: ${service.database.username}
      DB_TYPE: postgresdb
      GENERIC_TIMEZONE: ${default.timezone}
      N8N_HOST: ${service.fqdn}
      N8N_PROTOCOL: https
      WEBHOOK_URL: ${service.url}
    image: n8nio/n8n
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 5678}}"
    restart: unless-stopped
    volumes:
      - data:/home/node/.n8n
volumes:
  data:
  postgres:
