networks:
  default:
    external: true
    name: docker
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${SERVICE_DATABASE_PASSWORD}
      POSTGRES_USER: nocodb
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  service:
    depends_on:
      - postgres
    environment:
      NC_DB: pg://nocodb-postgres-1:5432?u=nocodb&p=${SERVICE_DATABASE_PASSWORD}&d=nocodb
    image: nocodb/nocodb
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/usr/app/data
volumes:
  data:
  postgres:
