networks:
  default:
    external: true
    name: docker
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${service.database_password}
      POSTGRES_USER: ${service.service}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  service:
    depends_on:
      - postgres
    environment:
      NC_DB: pg://${service.service}-postgres-1:5432?u=${service.service}&p=${service.database_password}&d=${service.service}
    image: nocodb/nocodb
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/usr/app/data
volumes:
  data:
  postgres:
