env_file:
  - path: ~/.env/_server.env
    required: false
  - path: ~/.env/open-webui.env
    required: false
networks:
  default:
    external: true
    name: docker
services:
  service:
    image: ghcr.io/open-webui/open-webui
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
volumes:
  data:
