networks:
  default:
    external: true
    name: docker
services:
  external:
    image: openspeedtest/latest
    labels:
      caddy: ${service.service}.${server.fqdn_external}
      caddy.import: external
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
  internal:
    image: openspeedtest/latest
    labels:
      caddy: ${service.service}.${server.fqdn_internal}
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
