networks:
  default:
    external: true
    name: docker
services:
  service:
    image: ghcr.io/open-webui/open-webui
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.import: ${SERVICE_ZONE}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - data:/app/backend/data
volumes:
  data:
