networks:
  default:
    external: true
    name: docker
services:
  external:
    image: openspeedtest/latest
    labels:
      caddy: speedtest.${SERVER_FQDN_EXTERNAL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
  internal:
    image: openspeedtest/latest
    labels:
      caddy: speedtest.${SERVER_FQDN_INTERNAL}
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: unless-stopped
