networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      REDLIB_DEFAULT_SUBSCRIPTIONS: apple+askanaustralian+ausfinance+aussiefrugal+australia+catastrophicfailure+datahoarder+emulation+emulationonandroid+flashlight+flipperzero+games+handhelds+hardware+homeassistant+homelab+homenetworking+internetisbeautiful+korea+linux+living_in_korea+minilab+minimalism+minipcs+movies+odinhandheld+outoftheloop+retroarch+retroid+roms+sbcgaming+selfhosted+sideloaded+space+steamdeck+sydney+sysadmin+television+thatlookedexpensive+trance+travel+trimui
      REDLIB_ROBOTS_DISABLE_INDEXING: on
    image: quay.io/redlib/redlib
    labels:
      caddy: ${service.fqdn}
      caddy.import: ${service.zone}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
