networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      REDLIB_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION: on
      REDLIB_DEFAULT_HIDE_AWARDS: on
      REDLIB_DEFAULT_SUBSCRIPTIONS: apple+askanaustralian+ausfinance+aussiecasual+australia+catastrophicfailure+datahoarder+emulation+emulationonandroid+flashlight+flipperzero+handhelds+hardware+homelab+homenetworking+internetisbeautiful+korea+linux+living_in_korea+minilab+minimalism+minipc+minipcs+miyoomini+movies+odinhandheld+outoftheloop+programmerhumor+retroarch+retroid+roms+sbcgaming+selfhosted+sideloaded+space+steamdeck+sydney+sysadmin+television+trance+travel
      REDLIB_DEFAULT_USE_HLS: on
      REDLIB_ROBOTS_DISABLE_INDEXING: on
      REDLIB_SFW_ONLY: on
    image: quay.io/redlib/redlib
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
