env_file:
  - path: ~/.env/syncthing.env
services:
  service:
    image: syncthing/syncthing
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.reverse_proxy: host.docker.internal:8384
    network_mode: host
    restart: unless-stopped
    volumes:
      - data:/var/syncthing
      - /home/max.schaefer:/sync
volumes:
  data:
