networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      PGID: 1000
      PUID: 1000
    hostname: ${SERVER_HOST}
    image: syncthing/syncthing
    labels:
      caddy: ${SERVICE_FQDN}
      caddy.import: internal
      caddy.reverse_proxy: "{{upstreams 8384}}"
    ports:
      - 22000:22000
      - 22000:22000/udp
    restart: unless-stopped
    volumes:
      - data:/var/syncthing
      - /home/max.schaefer:/sync
volumes:
  data:
