networks:
  default:
    external: true
    name: docker
services:
  service:
    environment:
      TZ: ${SERVER_TIMEZONE}
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_NOTIFICATION_URL: smtp://resend:${SERVER_RESEND_API_KEY}@smtp.resend.com:465/?from=${SERVER_EMAIL}&to=${SERVER_EMAIL}
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${SERVER_HOST}
      WATCHTOWER_POLL_INTERVAL: 43200
      WATCHTOWER_REMOVE_VOLUMES: true
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
