networks:
  default:
    external: true
    name: caddy
services:
  cronicle-edge:
    entrypoint: manager
    environment:
      CRONICLE_secret_key: ${WEBSITE_SECRET_HASH}
      TZ: ${DEFAULT_TIMEZONE}
    hostname: cronicle-edge
    image: ghcr.io/maxexcloo/cronicle-edge
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 3012}}"
      caddy.tls.dns: cloudflare ${SERVER_CLOUDFLARE_API_TOKEN}
      caddy.tls.resolvers: 1.1.1.1
    restart: unless-stopped
    volumes:
      - cronicle_data:/opt/cronicle/data
  tailscale:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TS_ACCEPT_DNS: true
      TS_AUTHKEY: ${WEBSITE_TAILSCALE_TAILNET_KEY}
      TS_EXTRA_ARGS: --accept-routes
      TS_USERSPACE: false
    image: tailscale/tailscale
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun
volumes:
  cronicle_data:
