networks:
  default:
    external: true
    name: caddy
services:
  cronicle-edge:
    entrypoint: manager
    environment:
      CRONICLE_manager: 1
      CRONICLE_secret_key: ${WEBSITE_SECRET_HASH}
      TZ: ${DEFAULT_TIMEZONE}
    image: ghcr.io/maxexcloo/cronicle-edge:latest
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 3012}}"
    restart: unless-stopped
    volumes:
      - cronicle_data:/opt/cronicle/data
volumes:
  cronicle_data:
