%{ for category, services in services ~}
%{ if length(services) > 0 ~}
- ${category}:
%{ for service, widget in services ~}
  - ${service}:
      ${indent(6, yamlencode(widget))}
%{ endfor ~}
%{ endif ~}
%{ endfor ~}
