%{ for server, services in services ~}
%{ if length(services) > 0 ~}
- ${server}:
%{ for service, variables in services ~}
  - ${service}:
      ${indent(6, yamlencode(variables))}
%{ endfor ~}
%{ endif ~}
%{ endfor ~}
