headerStyle: clean
title: ${homepage.title}
layout:
%{ for service_name, service in services ~}
%{ if length(try(service.widgets, [])) > 0 && try(service.has_href, true) ~}
  ${try(service.group, "Uncategorized")}:
    columns: 4
    style: row
%{ endif ~}
%{ endfor ~}
