hideVersion: true
title: ${homepage.title}
layout:
%{ for category, services in services ~}
%{ if length(services) > 0 ~}
  ${split(" - ", category)[1]}:
    columns: 4
    style: row
%{ endif ~}
%{ endfor ~}
