networks:
  default:
    external: true
    name: caddy
services:
  kasm:
    environment:
      KASM_PORT: 3443
      TZ: ${DEFAULT_TIMEZONE}
    image: linuxserver/kasm
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 3443}}"
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.tls_insecure_skip_verify:
    ports:
      - 3000:3000
      - 3443:3443
    privileged: true
    restart: unless-stopped
    volumes:
      - kasm_opt:/opt
      - kasm_profiles:/profiles
volumes:
  kasm_opt:
  kasm_profiles:
