alerting:
  email:
    default-alert:
      description: "${gatus.title} Check Failed"
      failure-threshold: 5
      send-on-resolved: true
      success-threshold: 5
    from: "${default.email}"
    host: "smtp.resend.com"
    password: "$${RESEND_API_KEY}"
    port: 587
    to: "${default.email}"
    username: "resend"
endpoints:
%{ for k, server in servers ~}
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "${tags[server.tag]}"
    name: "${k} (${server.title})"
    url: "icmp://${k}"
%{ endfor ~}
%{ for service in services ~}
%{ if service.enable_monitoring && service.fqdn != null ~}
  - alerts:
      - type: email
%{ if service.enable_ssl_validation == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if service.enable_ssl && service.enable_ssl_validation ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "${service.group}"
    name: "${service.title} (${service.server != null ? service.server : service.platform})"
    url: "${service.url}${service.monitoring_path}"
%{ endif ~}
%{ endfor ~}
ui:
  description: "${gatus.description}"
  header: "${gatus.title}"
  title: "${gatus.title}"
