alerting:
  email:
    default-alert:
      description: ${gatus.title} Check Failed
      failure-threshold: 5
      send-on-resolved: true
      success-threshold: 5
    from: ${default.email}
    host: ${terraform.resend.smtp_host}
    password: $${RESEND_API_KEY}
    port: ${terraform.resend.smtp_port}
    to: ${default.email}
    username: ${terraform.resend.smtp_username}
endpoints:
%{ for k, server in servers ~}
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "${tags[server.tag]}"
    name: "${k} (${server.title})"
    url: "icmp://${k}"
%{ endfor ~}
%{ for service in services ~}
%{ if service.enable_monitoring && service.fqdn != null && service.group != default.service_config.group && service.title != default.service_config.title ~}
  - alerts:
      - type: email
%{ if service.enable_ssl_validation == false ~}
    client:
      insecure: true
%{ endif ~}
    conditions:
%{ if service.enable_ssl && service.enable_ssl_validation ~}
      - "[CERTIFICATE_EXPIRATION] > 48h"
%{ endif ~}
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (${service.group})"
    name: "${service.title} (${service.server != null ? service.server : service.platform})"
    url: "${service.url}"
%{ endif ~}
%{ endfor ~}
ui:
  description: ${gatus.description}
  header: ${gatus.title}
  title: ${gatus.title}
