alerting:
  email:
    default-alert:
      description: "Excloo Uptime Check Failed"
      failure-threshold: 5
      send-on-resolved: true
      success-threshold: 5
    from: "max@excloo.com"
    host: "smtp.resend.com"
    password: "${RESEND_API_KEY}"
    port: 587
    to: "max@excloo.com"
    username: "resend"
endpoints:
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Routers"
    name: "au (AU)"
    url: "icmp://au"
  - alerts:
      - type: email
    client:
      insecure: true
    conditions:
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "UniFi (au)"
    url: "https://au.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (Physical)"
    name: "au-mini (Mini)"
    url: "icmp://au-mini"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (VMs)"
    name: "au-oracle (Oracle)"
    url: "icmp://au-oracle"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (Physical)"
    name: "au-pie (Pie)"
    url: "icmp://au-pie"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "Proxmox (au-pie)"
    url: "https://pie.au.excloo.org:8006"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (VMs)"
    name: "au-pie-haos (Pie HAOS)"
    url: "icmp://au-pie-haos"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "Home Assistant (au-pie-haos)"
    url: "https://haos.pie.au.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (VMs)"
    name: "au-pie-truenas (Pie TrueNAS)"
    url: "icmp://au-pie-truenas"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "TrueNAS (au-pie-truenas)"
    url: "https://truenas.pie.au.excloo.org:8443"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Routers"
    name: "kr (KR)"
    url: "icmp://kr"
  - alerts:
      - type: email
    conditions:
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "OpenWRT (kr)"
    url: "http://kr.excloo.org:81"
  - alerts:
      - type: email
    conditions:
      - "[CONNECTED] == true"
    group: "Servers (Physical)"
    name: "kr-kimbap (Kimbap TrueNAS)"
    url: "icmp://kr-kimbap"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (Servers)"
    name: "TrueNAS (kr-kimbap)"
    url: "https://kimbap.kr.excloo.org:8443"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "CubeBackup (au-pie-truenas)"
    url: "https://cubebackup.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo Books (au-mini)"
    url: "https://books.excloo.com"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo Chat (au-mini)"
    url: "https://chat.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo Convert (au-oracle)"
    url: "https://convert.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo Home (au-mini)"
    url: "https://home.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo N8N (au-oracle)"
    url: "https://n8n.excloo.com"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo NocoDB (au-oracle)"
    url: "https://nocodb.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo PDF (au-oracle)"
    url: "https://pdf.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo Photos (au-mini)"
    url: "https://photos.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo Reader (au-oracle)"
    url: "https://reader.excloo.com"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo Reddit (au-oracle)"
    url: "https://reddit.excloo.com"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo RSSHub (au-oracle)"
    url: "https://rsshub.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Excloo Tools (au-oracle)"
    url: "https://tools.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Grafana (au-pie-truenas)"
    url: "https://grafana.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Loki (au-pie-truenas)"
    url: "https://loki.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "MySpeed (au-mini)"
    url: "https://myspeed.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Portainer (au-mini)"
    url: "https://portainer.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Prometheus (au-pie-truenas)"
    url: "https://prometheus.excloo.org"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo Uptime (fly)"
    url: "https://uptime.excloo.com"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Node-RED (au-pie-haos)"
    url: "https://haos.pie.au.excloo.org:1880"
  - alerts:
      - type: email
    conditions:
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Syncthing (au-mini)"
    url: "http://mini.au.excloo.org:8384"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "File Browser (kr-kimbap)"
    url: "https://kimbap.kr.excloo.org:30051"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "File Browser (au-pie-truenas)"
    url: "https://truenas.pie.au.excloo.org:30051"
  - alerts:
      - type: email
    conditions:
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Syncthing (kr-kimbap)"
    url: "http://kimbap.kr.excloo.org:20910"
  - alerts:
      - type: email
    conditions:
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.org)"
    name: "Syncthing (au-pie-truenas)"
    url: "http://truenas.pie.au.excloo.org:20910"
  - alerts:
      - type: email
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[RESPONSE_TIME] < 5000"
      - "[STATUS] == any(200, 401)"
    group: "Services (excloo.com)"
    name: "Excloo GitHub Readme Stats (vercel)"
    url: "https://github-readme-stats.excloo.com"
ui:
  description: ""
  header: "Excloo Uptime"
  title: "Excloo Uptime"
