services:
  syncthing:
    image: syncthing/syncthing
    network_mode: host
    restart: unless-stopped
    volumes:
      - syncthing_data:/var/syncthing
      - /home/max.schaefer:/sync
volumes:
  syncthing_data:
