networks:
  default:
    external: true
    name: caddy
services:
  syncthing:
    image: syncthing/syncthing
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: host.docker.internal:8384
      caddy.tls.dns: cloudflare ${SERVER_CLOUDFLARE_API_TOKEN}
      caddy.tls.resolvers: 1.1.1.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/max.schaefer:/var/syncthing
