networks:
  default:
    external: true
    name: caddy
services:
  nocodb:
    environment:
      NC_DB: pg://postgres:5432?u=${WEBSITE_APP_TYPE}&p=${WEBSITE_DATABASE_PASSWORD}&d=${WEBSITE_APP_TYPE}
    image: nocodb/nocodb
    labels:
      caddy: ${WEBSITE_FQDN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
    restart: unless-stopped
    volumes:
      - nocodb_data:/usr/app/data
  postgres:
    environment:
      POSTGRES_PASSWORD: ${WEBSITE_DATABASE_PASSWORD}
      POSTGRES_USER: ${WEBSITE_APP_TYPE}
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  nocodb_data:
  postgres_data:
