scrape_configs:
%{ for service in services ~}
%{ for server_name, server in servers ~}
%{ if server_name == service.server || contains(server.services.*.service, service.service) ~}
  - job_name: '${service.service}-${server_name}'
    metrics_path: '${service.metrics_path}'
    scheme: '${service.enable_ssl ? "https" : "http"}'
%{ if can(service.config.metrics_token) ~}
    authorization:
      credentials: '${service.config.metrics_token}'
%{ endif ~}
%{ if can(service.config.metrics_token) == false && (can(service.config.metrics_password) || can(service.config.metrics_username) || service.enable_password || service.enable_secret_hash) ~}
    basic_auth:
      username: '${can(service.config.metrics_username) ? service.config.metrics_username : service.username != null ? service.username : server.secret_hash}'
      password: '${can(service.config.metrics_password) ? service.config.metrics_password : service.enable_password ? service.password : service.secret_hash}'
%{ endif ~}
    static_configs:
      - targets: ['${service.fqdn != null ? service.fqdn : "${service.service}.${server.fqdn_internal}"}']
        labels:
          location: '${server.location}'
          name: '${service.name}'
          server: '${server_name}'
          service: '${service.service}'
%{ endif ~}
%{ endfor ~}
%{ endfor ~}
