name: Check Changes & Deploy

on:
  push:
    paths:
      - "**/*"
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate Matrix
    outputs:
      matrix: ${{ env.MATRIX }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate matrix
        id: set-matrix
        run: |
          COMPARE_1=$(git rev-parse HEAD~1)
          COMPARE_2=$(git rev-parse HEAD)
          DIRS=$(find . -maxdepth 1 -mindepth 1 -not -name ".*" -type d)
          FIRST=true

          MATRIX="{\"include\":["
          for DIR in $DIRS; do
            if [ "${{ github.event_name }}" == "workflow_dispatch" ] || ! git diff --quiet "$COMPARE_1" "$COMPARE_2" -- "$DIR"; then
              if [ "$FIRST" = true ]; then
                FIRST=false
              else
                MATRIX="$MATRIX,"
              fi
              MATRIX="$MATRIX{\"dir\":\"${DIR#./}\"}"
            fi
          done
          MATRIX="$MATRIX]}"

          echo "MATRIX=$MATRIX" >> $GITHUB_ENV

  check-changes-and-deploy:
    if: ${{ needs.generate-matrix.outputs.matrix != '{"include":[]}' }}
    name: Check Changes & Deploy
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: pip install requests

      - name: Deploy ${{ matrix.dir }} to Portainer
        run: python deploy.py "${{ matrix.dir }}"
        env:
          PORTAINER_API_TOKEN: ${{ secrets.PORTAINER_API_TOKEN }}
          PORTAINER_URL: ${{ vars.PORTAINER_URL }}
          DEFAULTS: ${{ vars.DEFAULTS }}
          SERVERS: ${{ secrets.SERVERS }}
          WEBSITES: ${{ secrets.WEBSITES }}
