name: Deploy Fly Services

on:
  workflow_dispatch:
  push:
    paths:
      - "fly/*"

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate matrix
        id: generate-matrix
        run: |
          DIRS=$(find . -maxdepth 1 -mindepth 1 -type d)
          MATRIX=$(echo $DIRS | jq -R 'split(" ") | map({dir: .}) | {include: .}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  deploy:
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix).include[0] }}
    name: Deploy to Fly
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy ${{ matrix.dir }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
