name: Deploy Fly Services

on:
  push:
    paths:
      - "fly/**"
  workflow_dispatch:

env:
  WORKING_DIRECTORY: fly

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Generate matrix
        id: generate-matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            SERVICES=$(find ${{ env.WORKING_DIRECTORY }} -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | jq -c -s -R 'split("\n")[:-1]')
          else
            CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD -- ${{ env.WORKING_DIRECTORY }} | xargs -I {} dirname {} | sort -u | sed "s|${{ env.WORKING_DIRECTORY }}/||" | grep -v "^${{ env.WORKING_DIRECTORY }}$")
            SERVICES=$(echo "$CHANGED_DIRS" | jq -c -s -R 'split("\n")[:-1]')
          fi
          echo "matrix=$SERVICES" >> $GITHUB_OUTPUT

  deploy:
    if: needs.generate-matrix.outputs.matrix != '[]'
    name: Deploy to Fly
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy "${{ env.WORKING_DIRECTORY }}/${{ matrix.service }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        service: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
