name: Deploy Fly Services

on:
  push:
    paths:
      - "fly/*"
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate matrix
        id: generate-matrix
        run: |
          DIRS=$(find fly -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | jq -c -s -R 'split("\n")[:-1]')
          echo "matrix=$DIRS" >> $GITHUB_OUTPUT

  deploy:
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix)[0] }}
    name: Deploy to Fly
    needs: generate-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy fly/${{ matrix.dir }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        dir: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
